### ISSUE TITLE
Errors when running the test data

### ISSUE THREAD

**Issue by yangxiaofeill** [ENCODE-DCC/hic-pipeline#41]
Dear, 
       Thanks for your work on the hic-pipeline. I have downloaded the pipeline and installed like "https://github.com/ENCODE-DCC/hic-pipeline/blob/dev-1/docs/tutorial_local_docker.md".
       The docker version is `Docker version 18.03.0-ce, build 0520e24`, and the Java version is `OpenJDK Runtime Environment (build 1.8.0_141-b16`.
        However, when I run the test data as the following command
```
$ INPUT=examples/template_one.json 
$ PIPELINE_METADATA=metadata.json
$ java -jar -Dconfig.file=backends/backend.conf cromwell-37.jar run workflow/main_workflow/hic.wdl -i ${INPUT} -o workflow_opts/docker.json -m ${PIPELINE_METADATA}
```

There are some error messages, and a part of them like:
```
[2019-05-16 03:18:59,57] [warn] Local [70094ee5]: Key/s [cpu, disks, memory] is/are not supported by backend. Unsupported attributes will not be part of job executions.
[2019-05-16 03:19:01,89] [error] WorkflowManagerActor Workflow 70094ee5-a423-4353-b710-b87f5808ede3 failed (during ExecutingWorkflowState): java.lang.RuntimeException: Failed to evaluate 'hic.ligation_junction' (reason 1 of 1): Evaluating if defined(restriction_enzyme) then restriction_enzyme_to_site[restriction_enzyme] else "" failed: Failed to find a key 'Success(WomOptionalValue(WomStringType,Some(WomString(MboI))))' on a map:

Success(WomMap(WomMapType(WomStringType,WomStringType),Map(WomString(HindIII) -> WomString(AAGCTAGCTT), WomString(DpnII) -> WomString(GATCGATC), WomString(MboI) -> WomString(GATCGATC))))
        at cromwell.engine.workflow.lifecycle.execution.keys.ExpressionKey.processRunnable(ExpressionKey.scala:29)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.$anonfun$startRunnableNodes$7(WorkflowExecutionActor.scala:510)
        at cats.instances.ListInstances$$anon$1.$anonfun$traverse$2(list.scala:73)
        at cats.instances.ListInstances$$anon$1.loop$2(list.scala:63)
        at cats.instances.ListInstances$$anon$1.$anonfun$foldRight$1(list.scala:63)
        at cats.Eval$.loop$1(Eval.scala:341)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:372)
        at cats.Eval$Defer.value(Eval.scala:258)
        at cats.instances.ListInstances$$anon$1.traverse(list.scala:72)
        at cats.instances.ListInstances$$anon$1.traverse(list.scala:12)
        at cats.Traverse$Ops.traverse(Traverse.scala:19)
        at cats.Traverse$Ops.traverse$(Traverse.scala:19)
        at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:19)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor.cromwell$engine$workflow$lifecycle$execution$WorkflowExecutionActor$$startRunnableNodes(WorkflowExecutionActor.scala:504)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:186)
        at cromwell.engine.workflow.lifecycle.execution.WorkflowExecutionActor$$anonfun$5.applyOrElse(WorkflowExecutionActor.scala:184)
        at scala.PartialFunction$OrElse.apply(PartialFunction.scala:168)
        at akka.actor.FSM.processEvent(FSM.scala:687)
        at akka.actor.FSM.processEvent$(FSM.scala:681)
```

I don't know why, and could you help me to address this?

Thanks

**Comment by paul-sud** [comment]
Hi there, sorry for the late response, I didn't seem to get a notification upon your comment.

We are aware of this issue and are working on a fix (see https://github.com/ENCODE-DCC/hic-pipeline/tree/PIP-622-enzyme-bugfix for more details). I would recommend that you either check out the branch "PIP-546-entrypoint-after-libraries" or checkout the commit 85c938cffde814f36b8174757ea504b52912d99f on dev-1.  I can confirm that I have successfully ran the pipeline at that point.

Apologies for any inconvenience with this, unfortunately this bug was not caught by our test suite for reasons I do not yet understand.
