### ISSUE TITLE
Croo: list index out of range

### ISSUE THREAD

**Issue by guma44** [ENCODE-DCC/hic-pipeline#94]
Hi,
I am testing the pipeline and I can get it to finish successfully. However, when I try to copy the data with Croo package I get this error:
```
Traceback (most recent call last):
  File "/home/gumiera1/projects/cbtd-backend/dist/venv/bin/croo", line 13, in <module>
    main()
  File "/home/gumiera1/projects/cbtd-backend/dist/venv/lib/python3.7/site-packages/croo/cli.py", line 244, in main
    no_checksum=args['no_checksum'],
  File "/home/gumiera1/projects/cbtd-backend/dist/venv/lib/python3.7/site-packages/croo/croo.py", line 69, in __init__
    self._cm = CromwellMetadata(self._metadata)
  File "/home/gumiera1/projects/cbtd-backend/dist/venv/lib/python3.7/site-packages/croo/cromwell_metadata.py", line 102, in __init__
    self.__parse_calls(self._metadata_json['calls'])
  File "/home/gumiera1/projects/cbtd-backend/dist/venv/lib/python3.7/site-packages/croo/cromwell_metadata.py", line 151, in __parse_calls
    task_alias = call_name.split('.')[1]
IndexError: list index out of range
```

It is caused by the fact that Cromwell names nested scatter loops without prefix. Here is more detail: https://github.com/broadinstitute/cromwell/issues/4820. I can solve the error by embedding the line with `try-except` clause but the copying of the `align` will be skipped then. Before I would jump into fixing this I would like to ask if this works for you (and I am doing something wrong) or this is not working in general?

Best,
Rafal

**Comment by paul-sud** [comment]
I just checked, it does not work for me either. I am reaching out to the team for more information, I'll keep you updated here.

**Comment by guma44** [comment]
@paul-sud Thanks a lot!

**Comment by leepc12** [comment]
@guma44: Fixed. please update `croo` and try again.
https://github.com/ENCODE-DCC/croo/releases/tag/v0.6.0

```bash
$ pip install croo --upgrade
```

**Comment by paul-sud** [comment]
Hi @guma44 , were you able to resolve this issue with a newer version of `croo`?
